### PR TITLE
fail when kubeadm init fails

### PR DESCRIPTION
**Pull request by rdxmb**
Do not allow init errors 
see https://github.com/geerlingguy/ansible-role-kubernetes/issues/28

result (here with a non-existing kubernetes-version):
```
[...]
TASK [kubernetes : Initialize Kubernetes master with kubeadm init.] *************************
fatal: [eins.mbr.intern]: FAILED! => {"changed": true, "cmd": ["kubeadm", "init", "--pod-network-cidr=10.244.0.0/16", "--apiserver-advertise-address=", "--kubernetes-version", "stable-1.13.", "--ignore-preflight-errors=all"], "delta": "0:00:01.073684", "end": "2019-01-02 14:39:41.933897", "msg": "non-zero return code", "rc": 1, "start": "2019-01-02 14:39:40.860213", "stderr": "unable to fetch file. URL: \"https://dl.k8s.io/release/stable-1.13..txt\", status: 404 Not Found", "stderr_lines": ["unable to fetch file. URL: \"https://dl.k8s.io/release/stable-1.13..txt\", status: 404 Not Found"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT **************************************************************************
        to retry, use: --limit @/home/marc/infrastructure/kubernetes/playbooks/mbr.debug.retry
```

### CODE REVIEW

**Comment by Ilshidur** [comment]
Working for me !
Can this be merged ?

**Comment by geerlingguy** [comment]
Hmm... I still want to make sure kubeadm init output can be displayed if someone has more verbosity turned on. Can we still achieve that goal along with making the task fail if init fails?

**Comment by rdxmb** [comment]
@geerlingguy  I actually do not understand why the task does *not* fail on errors in your code. Which line does prevent that?

`failed_when: false` ?

**Comment by geerlingguy** [comment]
@rdxmb - Yes, and I'm not 100% sure the reason I added it in the first place, it might've been because even with preflight errors ignored, there would be a non-0 exit code? Or maybe some stderr output? Not sure.

**Comment by geerlingguy** [comment]
> Hmm... I still want to make sure kubeadm init output can be displayed if someone has more verbosity turned on. Can we still achieve that goal along with making the task fail if init fails?

Answering myself here... if you run with `-vvvv` all the output is displayed (stdout and stderr). But the task still may fail if there are just warnings during setup, and that may have been my original motivation.

**Comment by rdxmb** [comment]
@geerlingguy could you make an example for that?

**Comment by edigaryev** [comment]
>But the task still may fail if there are just warnings during setup

This doesn't seem to be the case, at least on 1.16:

```
# kubeadm init 
I0313 00:07:31.488506   31768 version.go:251] remote version is much newer: v1.17.4; falling back to: stable-1.16
[init] Using Kubernetes version: v1.16.8
[preflight] Running pre-flight checks
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.8. Latest validated version: 18.09
	[WARNING Hostname]: hostname "n1" could not be reached
	[WARNING Hostname]: hostname "n1": lookup n1 on 8.8.8.8:53: no such host
[...]
Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:
[...]
```

```
# echo $?
0
```

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:31:27Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

I've wasted a couple hours diagnosing the wrong problem due to this `failed_when: false` behavior before I've stumbled into this PR.

**Pull request merged**
